api:
  version: /v1

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/agenda
    username: agenda_user
    password: changeit
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  management:
    endpoints:
      web:
        exposure:
          include: health,info        # ou "*" para todos
